"""initial schema

Revision ID: e3cd55308ea0
Revises:
Create Date: 2026-07-07 18:25:26.814156

Hand-written rather than autogenerated: RDS Data API's result deserialization
doesn't support the CHAR result type that Alembic's autogenerate reflection
query against information_schema.columns produces (UnsupportedResultException).
Not a problem for an initial migration — there's nothing to diff against
yet, and this file only executes DDL (create_table/create_index), which the
Data API handles fine; it's schema *reflection* (SELECT queries returning
CHAR columns) that's unsupported, not DDL execution.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from common.models import Vector

# revision identifiers, used by Alembic.
revision: str = "e3cd55308ea0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

AGENT_MEMORY_EMBEDDING_DIM = 1024


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "claims",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("s3_key", sa.String(), nullable=False, unique=True),
        sa.Column("document_type", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="processing"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "extractions",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "claim_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("claims.id"),
            nullable=False,
        ),
        sa.Column("fields", sa.dialects.postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column(
            "field_confidences", sa.dialects.postgresql.JSONB(), nullable=False, server_default="{}"
        ),
        sa.Column("parse_confidence", sa.Float(), nullable=True),
        sa.Column("extract_confidence", sa.Float(), nullable=True),
        sa.Column("completeness_score", sa.Float(), nullable=True),
        sa.Column("composite_confidence", sa.Float(), nullable=True),
        sa.Column("is_automated", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "reviews",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "extraction_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("extractions.id"),
            nullable=False,
        ),
        sa.Column("reviewer_email", sa.String(), nullable=False),
        sa.Column("verdict", sa.String(), nullable=False),
        sa.Column("corrected_fields", sa.dialects.postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "review_metrics",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("reviewer_email", sa.String(), nullable=False),
        sa.Column("metric_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rejected_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("corrected_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint(
            "reviewer_email", "metric_date", name="uq_review_metrics_reviewer_date"
        ),
    )

    op.create_table(
        "agent_memory",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(AGENT_MEMORY_EMBEDDING_DIM), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # HNSW index for cosine-similarity search over agent memory.
    op.execute(
        "CREATE INDEX ix_agent_memory_embedding_hnsw "
        "ON agent_memory USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_agent_memory_embedding_hnsw")
    op.drop_table("agent_memory")
    op.drop_table("review_metrics")
    op.drop_table("reviews")
    op.drop_table("extractions")
    op.drop_table("claims")
